# Water Quality Index Analysis

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
# بارگذاری فایل CSV
df = pd.read_csv("data/water_quality_data.csv")

# نمایش ۵ سطر اول
df.head()

In [ ]:
# بررسی اطلاعات آماری
df.describe()

In [ ]:
# بررسی مقادیر گمشده
df.isnull().sum()